name: Build and upload artifact

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./prepare-flatcar-sdk.sh
        env:
          FLATCAR_VERSION: flatcar-3033
      - run: ./build-crio.sh
      
